### PR TITLE
Updated to API 1.22 and fixed bugs (can't open signs, plugin don't create new sign in database)

### PR DESCRIPTION
**Pull request by mistzzt**
Updated to API 1.22 and replaced references. 
Changed the target framework from 4.0 to 4.5
Fixed bugs (can't open signs, plugin don't create new sign in database) caused by version updating of Terraria.

Note that: **Styles** of some changes displayed below are **not so good**, but I found that if I open code files in **visual studio**, they **look good**. 
The screen shot I uploaded will show you what I mean.

example

### CODE REVIEW

**Comment by mistzzt** [comment]
**The BUG I just found:**
The `CommandDelegate` of command **/spset** should be `Public`, not `Region`.
And in the original code, `void Public(CommandArgs e)` is **never used**.

```
Commands.ChatCommands.Add(new Command("infsigns.sign.public", Region, "spset")
            {
                AllowServer = false,
                HelpText = "Toggles a sign's public protection when read."
            });
            Commands.ChatCommands.Add(new Command("infsigns.sign.region", Region, "srset")
            {
                AllowServer = false,
                HelpText = "Toggles a sign's region protection when read."
            });
```

Methods:

```
void Public(CommandArgs e)
        {
            Infos[e.Player.Index].Action = SignAction.TogglePublic;
            e.Player.SendInfoMessage("Read a sign to toggle its public protection.");
        }
        void Region(CommandArgs e)
        {
            Infos[e.Player.Index].Action = SignAction.ToggleRegion;
            e.Player.SendInfoMessage("Read a sign to toggle its region protection.");
        }
```

However, I don't know whether it is a bug or it is just what the author wanted to do...
Because in the method `GetSign(int x, int y, int plr)`, it showed that:

```
case SignAction.TogglePublic:
player.SendInfoMessage("This sign is no{0} public.", sign.IsRegion ? " longer" : "w");
case SignAction.ToggleRegion:
player.SendInfoMessage("This sign is no{0} region shared.", sign.IsRegion ? " longer" : "w");
```

Both cases use the same property `IsRegion`, which makes me confused...

**Comment by mistzzt** [comment]
# **Update: bug fixed.** lol

Oh.. How can I delete this pull request?
I found that when this plugin was updated to the API 1.22, **it doesn't work**.
Anyway, I found the reason and i decided to take measures to fix it.

## Reason:

the method `void PlaceSign(int x, int y, int plr)` is **never called** because in the new version Terraria, client will send a Message which type is `PacketTypes.PlaceObject` when placing signs, but in the original codes(the plugin), `PlaceSign` would be called **only if the client send server a `PacketTypes.Tile` message**.

**Comment by QuiCM** [comment]
@mistzzt Only just noticed this PR. Did your above changes fix the plugin?

**Comment by mistzzt** [comment]
In this PR, I used spaces rather than TAB, so I closed it.

I think that these changes did fix the plugin, and I will open a new PR solving this.

**Comment by QuiCM** [comment]
Ahh, I see.
Thank you! :)

**Pull request closed without merging**
